#!/bin/sh

# Generate the hardware-specific LED list used by LED Control.  This helper is
# shared by the standalone installer and the OpenWrt package lifecycle script.

usage() {
	printf '%s\n' "Usage: $0 [--force] OUTPUT_FILE" >&2
}

detect_uci_leds() {
	command -v uci >/dev/null 2>&1 || return
	uci -q show system 2>/dev/null | \
		sed -n "s/^system\..*\.sysfs='\([^']*\)'$/\1/p"
}

get_led_alias_node() {
	alias_name="$1"

	for aliases_dir in /proc/device-tree/aliases /sys/firmware/devicetree/base/aliases; do
		[ -r "$aliases_dir/$alias_name" ] || continue
		tr -d '\000' < "$aliases_dir/$alias_name"
		return
	done
}

get_led_alias_name() {
	alias_node=$(get_led_alias_node "$1")
	[ -n "$alias_node" ] || return

	for tree_root in /proc/device-tree /sys/firmware/devicetree/base; do
		[ -r "$tree_root$alias_node/label" ] || continue
		tr -d '\000' < "$tree_root$alias_node/label"
		return
	done

	alias_node=${alias_node##*/}
	alias_node=${alias_node#led_}
	case "$alias_node" in
		*_*)
			function=${alias_node%_*}
			color=${alias_node##*_}
			printf '%s:%s' "$color" "$function"
			;;
	esac
}

generate_led_config() {
	uci_leds=$(detect_uci_leds)
	running_led_name=$(get_led_alias_name led-running)
	leds=""
	static_leds=""
	static_candidates=""

	for led in /sys/class/leds/*; do
		[ -d "$led" ] || continue
		[ -r "$led/trigger" ] && [ -w "$led/brightness" ] || continue

		led_name=${led##*/}
		leds="$leds $led"
		managed_by_uci=0

		for uci_led in $uci_leds; do
			[ "$led_name" = "$uci_led" ] && managed_by_uci=1
		done

		[ "$managed_by_uci" -eq 1 ] && continue

		case "$led_name" in
			power|status|system|running|*:power|*:status|*:system|*:running)
				static_candidates="$static_candidates $led"
				;;
		esac
	done

	for led in $static_candidates; do
		led_name=${led##*/}
		led_role=${led_name##*:}
		role_count=0

		for candidate in $static_candidates; do
			candidate_name=${candidate##*/}
			[ "${candidate_name##*:}" = "$led_role" ] && \
				role_count=$((role_count + 1))
		done

		if [ "$led_name" = "$running_led_name" ] || [ "$role_count" -eq 1 ]; then
			static_leds="$static_leds $led"
		fi
	done

	leds=${leds# }
	static_leds=${static_leds# }
	[ -n "$leds" ] || return 1

	{
		printf '%s\n' '# Generated by LED Control from /sys/class/leds'
		printf 'LEDS="%s"\n' "$leds"
		printf 'STATIC_ON_LEDS="%s"\n' "$static_leds"
	} > "$temporary_file"

	mv "$temporary_file" "$output_file"
	temporary_file=""
}

force=0

case "$1" in
	--force)
		force=1
		shift
		;;
esac

[ "$#" -eq 1 ] || {
	usage
	exit 1
}

output_file="$1"
[ -f "$output_file" ] && [ "$force" -eq 0 ] && exit 0

output_dir=${output_file%/*}
[ "$output_dir" != "$output_file" ] || output_dir=.
mkdir -p "$output_dir" || exit 1
temporary_file="$output_dir/.${output_file##*/}.$$"
trap 'rm -f "$temporary_file"' EXIT HUP INT TERM

generate_led_config || {
	printf '%s\n' 'ledcontrol: no controllable LEDs found in /sys/class/leds' >&2
	exit 1
}
