#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

CONTROL_SCRIPT=/etc/scripts/ledcontrol/ledcontrol.sh

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh -c "sleep 5; while true; do $CONTROL_SCRIPT auto; sleep 300; done"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
