#!/bin/sh

REPOSITORY="https://raw.githubusercontent.com/NikkyFreaky/OpenWRT/main/scripts/ledcontrol"
SCRIPT_DIR="/etc/scripts/ledcontrol"
CONTROL_SCRIPT="$SCRIPT_DIR/ledcontrol.sh"
CONFIG_FILE="$SCRIPT_DIR/ledcontrol.conf"
SETTINGS_FILE="/etc/config/ledcontrol"
LEGACY_SCRIPT="/etc/scripts/ledcontrol.sh"
LEGACY_PROFILE_DIR="$SCRIPT_DIR/profiles"
CRONTAB_FILE="/etc/crontabs/root"
RC_LOCAL="/etc/rc.local"
MODE_STATE_FILE="/tmp/ledcontrol.mode"
TEMP_DIR="/tmp/ledcontrol-install.$$"
CACHE_BUST="$(date +%s 2>/dev/null || printf '%s' "$$")"

msg() {
        printf '%s\n' "$*"
}

cleanup() {
        rm -rf "$TEMP_DIR"
}

download() {
        wget -q -O "$2" "$1?cachebust=$CACHE_BUST" && [ -s "$2" ]
}

detect_uci_leds() {
        command -v uci >/dev/null 2>&1 || return
        uci -q show system 2>/dev/null | \
                sed -n "s/^system\..*\.sysfs='\([^']*\)'$/\1/p"
}

get_led_alias_node() {
        alias_name="$1"

        for aliases_dir in /proc/device-tree/aliases /sys/firmware/devicetree/base/aliases; do
                [ -r "$aliases_dir/$alias_name" ] || continue
                tr -d '\000' < "$aliases_dir/$alias_name"
                return
        done
}

get_led_alias_name() {
        alias_node=$(get_led_alias_node "$1")
        [ -n "$alias_node" ] || return

        # Older Device Tree descriptions expose a label.  Newer descriptions
        # use the standard function/color properties, whose node name is
        # conventionally <function>_<color> (for example power_blue).
        for tree_root in /proc/device-tree /sys/firmware/devicetree/base; do
                [ -r "$tree_root$alias_node/label" ] || continue
                tr -d '\000' < "$tree_root$alias_node/label"
                return
        done

        alias_node=${alias_node##*/}
        alias_node=${alias_node#led_}
        case "$alias_node" in
                *_*)
                        function=${alias_node%_*}
                        color=${alias_node##*_}
                        printf '%s:%s' "$color" "$function"
                        ;;
        esac
}

generate_led_config() {
        uci_leds=$(detect_uci_leds)
        running_led_name=$(get_led_alias_name led-running)
        leds=""
        static_leds=""
        static_led_names=""
        static_candidates=""
        led_names=""
        led_count=0

        for led in /sys/class/leds/*; do
                [ -d "$led" ] || continue
                [ -r "$led/trigger" ] && [ -w "$led/brightness" ] || continue

                led_name=${led##*/}
                leds="$leds $led"
                led_names="$led_names $led_name"
                led_count=$((led_count + 1))
                managed_by_uci=0

                for uci_led in $uci_leds; do
                        [ "$led_name" = "$uci_led" ] && managed_by_uci=1
                done

                [ "$managed_by_uci" -eq 1 ] && continue

                case "$led_name" in
                        power|status|system|running|*:power|*:status|*:system|*:running)
                                static_candidates="$static_candidates $led"
                                ;;
                esac
        done

        # A multicolour LED can expose one sysfs entry per colour.  Prefer the
        # device-tree led-running alias (the platform's normal running state)
        # over enabling every colour.  If no alias is available, use only an
        # unambiguous single-colour power/status/system/running LED.
        for led in $static_candidates; do
                led_name=${led##*/}
                led_role=${led_name##*:}
                role_count=0

                for candidate in $static_candidates; do
                        candidate_name=${candidate##*/}
                        [ "${candidate_name##*:}" = "$led_role" ] && \
                                role_count=$((role_count + 1))
                done

                if [ "$led_name" = "$running_led_name" ] || [ "$role_count" -eq 1 ]; then
                        static_leds="$static_leds $led"
                        static_led_names="$static_led_names $led_name"
                fi
        done

        leds=${leds# }
        static_leds=${static_leds# }
        static_led_names=${static_led_names# }
        led_names=${led_names# }
        [ -n "$leds" ] || return 1

        {
                printf '%s\n' '# Generated by ledcontrol installer from /sys/class/leds'
                printf 'LEDS="%s"\n' "$leds"
                printf 'STATIC_ON_LEDS="%s"\n' "$static_leds"
        } > "$1"

        DETECTED_LED_COUNT="$led_count"
        DETECTED_LED_NAMES="$led_names"
        DETECTED_STATIC_LED_NAMES="$static_led_names"
}

remove_cron_entries() {
        [ -f "$CRONTAB_FILE" ] || return
        grep -Fv "$CONTROL_SCRIPT" "$CRONTAB_FILE" | \
                grep -Fv "$LEGACY_SCRIPT" > "$TEMP_DIR/crontab"
        mv "$TEMP_DIR/crontab" "$CRONTAB_FILE"
        [ -x /etc/init.d/cron ] && /etc/init.d/cron restart
}

install_cron() {
        mkdir -p /etc/crontabs
        touch "$CRONTAB_FILE"
        remove_cron_entries
        {
                cat "$CRONTAB_FILE"
                printf '%s\n' "*/5 * * * * $CONTROL_SCRIPT auto"
        } > "$TEMP_DIR/crontab.new"
        mv "$TEMP_DIR/crontab.new" "$CRONTAB_FILE"
        [ -x /etc/init.d/cron ] && /etc/init.d/cron restart
}

install_luci() {
        [ -d /www/luci-static/resources ] || {
                msg "LuCI is not installed; skipped the web interface"
                return
        }

        mkdir -p /www/luci-static/resources/view/ledcontrol
        mkdir -p /usr/share/luci/menu.d
        mkdir -p /usr/share/rpcd/acl.d
        mkdir -p /usr/lib/lua/luci/i18n
        mv "$TEMP_DIR/overview.js" /www/luci-static/resources/view/ledcontrol/overview.js
        mv "$TEMP_DIR/luci-app-ledcontrol.json" /usr/share/luci/menu.d/luci-app-ledcontrol.json
        mv "$TEMP_DIR/luci-app-ledcontrol.acl.json" /usr/share/rpcd/acl.d/luci-app-ledcontrol.json
        mv "$TEMP_DIR/ledcontrol.ru.lmo" /usr/lib/lua/luci/i18n/ledcontrol.ru.lmo

        # LuCI caches the page tree under /tmp.  Drop every versioned cache
        # file so a newly installed menu entry is visible immediately.
        rm -f /tmp/luci-indexcache.*.json

        if [ -x /etc/init.d/rpcd ]; then
                /etc/init.d/rpcd restart
        fi

        msg "LuCI interface installed; sign out and sign in again, then refresh the page"
}

remove_startup_entries() {
        startup_line="(sleep 5 && $CONTROL_SCRIPT auto) &"
        legacy_startup_line="(sleep 5 && $LEGACY_SCRIPT auto) &"

        [ -f "$RC_LOCAL" ] || return
        grep -Fvx "$startup_line" "$RC_LOCAL" | \
                grep -Fvx "$legacy_startup_line" > "$TEMP_DIR/rc.local"
        mv "$TEMP_DIR/rc.local" "$RC_LOCAL"
}

install_startup() {
        startup_line="(sleep 5 && $CONTROL_SCRIPT auto) &"

        if [ ! -f "$RC_LOCAL" ]; then
                printf '%s\n' '#!/bin/sh' '' 'exit 0' > "$RC_LOCAL"
        fi

        remove_startup_entries
        awk -v line="$startup_line" '
                $0 == "exit 0" && !inserted { print line; inserted = 1 }
                { print }
                END {
                        if (!inserted) {
                                print line
                                print "exit 0"
                        }
                }
        ' "$RC_LOCAL" > "$TEMP_DIR/rc.local.new"
        mv "$TEMP_DIR/rc.local.new" "$RC_LOCAL"
        chmod +x "$RC_LOCAL"
}

uninstall() {
        remove_cron_entries
        remove_startup_entries

        if [ -x /etc/init.d/led ]; then
                /etc/init.d/led restart
        fi

        rm -f /www/luci-static/resources/view/ledcontrol/overview.js
        rm -f /usr/share/luci/menu.d/luci-app-ledcontrol.json
        rm -f /usr/share/rpcd/acl.d/luci-app-ledcontrol.json
        rm -f /usr/lib/lua/luci/i18n/ledcontrol.ru.lmo
        rm -f /tmp/luci-indexcache.*.json
        rm -f "$MODE_STATE_FILE"
        rm -f "$SETTINGS_FILE"
        rm -f "$LEGACY_SCRIPT"
        rm -rf "$SCRIPT_DIR"

        if [ -x /etc/init.d/rpcd ]; then
                /etc/init.d/rpcd restart
        fi

        msg "ledcontrol has been removed"
}

main() {
        trap cleanup 0 INT TERM
        mkdir -p "$TEMP_DIR"

        case "$1" in
                uninstall)
                        uninstall
                        exit 0
                        ;;
                "")
                        ;;
                *)
                        msg "Usage: $0 [uninstall]"
                        exit 1
                        ;;
        esac

        download "$REPOSITORY/ledcontrol.sh" "$TEMP_DIR/ledcontrol.sh" || {
                msg "Unable to download ledcontrol.sh"
                exit 1
        }
        download "$REPOSITORY/defaults/ledcontrol" "$TEMP_DIR/ledcontrol.defaults" || {
                msg "Unable to download the default settings"
                exit 1
        }
        download "$REPOSITORY/luci/htdocs/luci-static/resources/view/ledcontrol/overview.js" "$TEMP_DIR/overview.js" || {
                msg "Unable to download the LuCI interface"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/share/luci/menu.d/luci-app-ledcontrol.json" "$TEMP_DIR/luci-app-ledcontrol.json" || {
                msg "Unable to download the LuCI menu"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/share/rpcd/acl.d/luci-app-ledcontrol.json" "$TEMP_DIR/luci-app-ledcontrol.acl.json" || {
                msg "Unable to download the LuCI access policy"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/lib/lua/luci/i18n/ledcontrol.ru.lmo" "$TEMP_DIR/ledcontrol.ru.lmo" || {
                msg "Unable to download the Russian LuCI translation"
                exit 1
        }
        generate_led_config "$TEMP_DIR/ledcontrol.conf" || {
                msg "No controllable LEDs found in /sys/class/leds"
                exit 1
        }
        msg "Detected LEDs: $DETECTED_LED_NAMES"
        msg "Static LEDs: ${DETECTED_STATIC_LED_NAMES:-none}"

        mkdir -p "$SCRIPT_DIR"
        mv "$TEMP_DIR/ledcontrol.sh" "$CONTROL_SCRIPT"
        mv "$TEMP_DIR/ledcontrol.conf" "$CONFIG_FILE"
        if [ ! -f "$SETTINGS_FILE" ]; then
                mkdir -p /etc/config
                mv "$TEMP_DIR/ledcontrol.defaults" "$SETTINGS_FILE"
        fi
        chmod 755 "$CONTROL_SCRIPT"
        if [ -e "$LEGACY_SCRIPT" ]; then
                rm -f "$LEGACY_SCRIPT"
                msg "Removed legacy ledcontrol installation"
        fi
        if [ -d "$LEGACY_PROFILE_DIR" ]; then
                rm -rf "$LEGACY_PROFILE_DIR"
                msg "Removed legacy LED profiles"
        fi
        install_cron
        install_startup
        install_luci
        "$CONTROL_SCRIPT" auto
        msg "ledcontrol installed for $DETECTED_LED_COUNT LED(s)"
}

main "$@"
