#!/bin/sh

REPOSITORY="https://raw.githubusercontent.com/NikkyFreaky/OpenWRT/main/scripts/ledcontrol"
SCRIPT_DIR="/etc/scripts/ledcontrol"
CONTROL_SCRIPT="$SCRIPT_DIR/ledcontrol.sh"
CONFIG_FILE="$SCRIPT_DIR/ledcontrol.conf"
SETTINGS_FILE="/etc/config/ledcontrol"
LEGACY_SCRIPT="/etc/scripts/ledcontrol.sh"
LEGACY_PROFILE_DIR="$SCRIPT_DIR/profiles"
CRONTAB_FILE="/etc/crontabs/root"
RC_LOCAL="/etc/rc.local"
TEMP_DIR="/tmp/ledcontrol-install.$$"
CACHE_BUST="$(date +%s 2>/dev/null || printf '%s' "$$")"

msg() {
        printf '%s\n' "$*"
}

cleanup() {
        rm -rf "$TEMP_DIR"
}

download() {
        wget -q -O "$2" "$1?cachebust=$CACHE_BUST" && [ -s "$2" ]
}

detect_uci_leds() {
        command -v uci >/dev/null 2>&1 || return
        uci -q show system 2>/dev/null | \
                sed -n "s/^system\..*\.sysfs='\([^']*\)'$/\1/p"
}

generate_led_config() {
        uci_leds=$(detect_uci_leds)
        leds=""
        static_leds=""
        led_names=""
        led_count=0

        for led in /sys/class/leds/*; do
                [ -d "$led" ] || continue
                [ -r "$led/trigger" ] && [ -w "$led/brightness" ] || continue

                led_name=${led##*/}
                leds="$leds $led"
                led_names="$led_names $led_name"
                led_count=$((led_count + 1))
                managed_by_uci=0

                for uci_led in $uci_leds; do
                        [ "$led_name" = "$uci_led" ] && managed_by_uci=1
                done

                [ "$managed_by_uci" -eq 1 ] && continue

                case "$led_name" in
                        power|status|system|running|*:power|*:status|*:system|*:running)
                                static_leds="$static_leds $led"
                                ;;
                esac
        done

        leds=${leds# }
        static_leds=${static_leds# }
        led_names=${led_names# }
        [ -n "$leds" ] || return 1

        {
                printf '%s\n' '# Generated by ledcontrol installer from /sys/class/leds'
                printf 'LEDS="%s"\n' "$leds"
                printf 'STATIC_ON_LEDS="%s"\n' "$static_leds"
        } > "$1"

        DETECTED_LED_COUNT="$led_count"
        DETECTED_LED_NAMES="$led_names"
}

install_cron() {
        mkdir -p /etc/crontabs
        touch "$CRONTAB_FILE"
        grep -Fv "$CONTROL_SCRIPT" "$CRONTAB_FILE" | \
                grep -Fv "$LEGACY_SCRIPT" > "$TEMP_DIR/crontab"
        {
                cat "$TEMP_DIR/crontab"
                printf '%s\n' "*/5 * * * * $CONTROL_SCRIPT auto"
        } > "$TEMP_DIR/crontab.new"
        mv "$TEMP_DIR/crontab.new" "$CRONTAB_FILE"
        /etc/init.d/cron restart
}

install_luci() {
        [ -d /www/luci-static/resources ] || {
                msg "LuCI is not installed; skipped the web interface"
                return
        }

        mkdir -p /www/luci-static/resources/view/ledcontrol
        mkdir -p /usr/share/luci/menu.d
        mkdir -p /usr/share/rpcd/acl.d
        mkdir -p /usr/lib/lua/luci/i18n
        mv "$TEMP_DIR/overview.js" /www/luci-static/resources/view/ledcontrol/overview.js
        mv "$TEMP_DIR/luci-app-ledcontrol.json" /usr/share/luci/menu.d/luci-app-ledcontrol.json
        mv "$TEMP_DIR/luci-app-ledcontrol.acl.json" /usr/share/rpcd/acl.d/luci-app-ledcontrol.json
        mv "$TEMP_DIR/ledcontrol.ru.lmo" /usr/lib/lua/luci/i18n/ledcontrol.ru.lmo

        # LuCI caches the page tree under /tmp.  Drop every versioned cache
        # file so a newly installed menu entry is visible immediately.
        rm -f /tmp/luci-indexcache.*.json

        if [ -x /etc/init.d/rpcd ]; then
                /etc/init.d/rpcd restart
        fi

        msg "LuCI interface installed; sign out and sign in again, then refresh the page"
}

install_startup() {
        startup_line="(sleep 5 && $CONTROL_SCRIPT auto) &"
        legacy_startup_line="(sleep 5 && $LEGACY_SCRIPT auto) &"

        if [ ! -f "$RC_LOCAL" ]; then
                printf '%s\n' '#!/bin/sh' '' 'exit 0' > "$RC_LOCAL"
        fi

        grep -Fvx "$startup_line" "$RC_LOCAL" | \
                grep -Fvx "$legacy_startup_line" > "$TEMP_DIR/rc.local"
        awk -v line="$startup_line" '
                $0 == "exit 0" && !inserted { print line; inserted = 1 }
                { print }
                END {
                        if (!inserted) {
                                print line
                                print "exit 0"
                        }
                }
        ' "$TEMP_DIR/rc.local" > "$TEMP_DIR/rc.local.new"
        mv "$TEMP_DIR/rc.local.new" "$RC_LOCAL"
        chmod +x "$RC_LOCAL"
}

main() {
        trap cleanup 0 INT TERM
        mkdir -p "$TEMP_DIR"

        download "$REPOSITORY/ledcontrol.sh" "$TEMP_DIR/ledcontrol.sh" || {
                msg "Unable to download ledcontrol.sh"
                exit 1
        }
        download "$REPOSITORY/defaults/ledcontrol" "$TEMP_DIR/ledcontrol.defaults" || {
                msg "Unable to download the default settings"
                exit 1
        }
        download "$REPOSITORY/luci/htdocs/luci-static/resources/view/ledcontrol/overview.js" "$TEMP_DIR/overview.js" || {
                msg "Unable to download the LuCI interface"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/share/luci/menu.d/luci-app-ledcontrol.json" "$TEMP_DIR/luci-app-ledcontrol.json" || {
                msg "Unable to download the LuCI menu"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/share/rpcd/acl.d/luci-app-ledcontrol.json" "$TEMP_DIR/luci-app-ledcontrol.acl.json" || {
                msg "Unable to download the LuCI access policy"
                exit 1
        }
        download "$REPOSITORY/luci/root/usr/lib/lua/luci/i18n/ledcontrol.ru.lmo" "$TEMP_DIR/ledcontrol.ru.lmo" || {
                msg "Unable to download the Russian LuCI translation"
                exit 1
        }
        generate_led_config "$TEMP_DIR/ledcontrol.conf" || {
                msg "No controllable LEDs found in /sys/class/leds"
                exit 1
        }
        msg "Detected LEDs: $DETECTED_LED_NAMES"

        mkdir -p "$SCRIPT_DIR"
        mv "$TEMP_DIR/ledcontrol.sh" "$CONTROL_SCRIPT"
        mv "$TEMP_DIR/ledcontrol.conf" "$CONFIG_FILE"
        if [ ! -f "$SETTINGS_FILE" ]; then
                mkdir -p /etc/config
                mv "$TEMP_DIR/ledcontrol.defaults" "$SETTINGS_FILE"
        fi
        chmod 755 "$CONTROL_SCRIPT"
        if [ -e "$LEGACY_SCRIPT" ]; then
                rm -f "$LEGACY_SCRIPT"
                msg "Removed legacy ledcontrol installation"
        fi
        if [ -d "$LEGACY_PROFILE_DIR" ]; then
                rm -rf "$LEGACY_PROFILE_DIR"
                msg "Removed legacy LED profiles"
        fi
        install_cron
        install_startup
        install_luci
        "$CONTROL_SCRIPT" auto
        msg "ledcontrol installed for $DETECTED_LED_COUNT LED(s)"
}

main "$@"
